### ISSUE TITLE
Tweak composer file to allow downloads w/ composer

### ISSUE THREAD

**Issue by mortona42** [mattwebdev/commerce_usps#1]
Need the file to download via composer. Also makes it easier to fetch the dependency.

**Comment by mortona42** [comment]
Err I'm blind, it's totally there. My composer refuses to install it though.

**Comment by mortona42** [comment]
Commerce UPS was missing the file, not this one.

Here's what I'm trying:
composer.json:
        {
            "type": "vcs",
            "url": "https://github.com/mattwebdev/commerce_usps"
        }

composer require commerce_usps/commerce_usps

returns:
Could not find package commerce_usps/commerce_usps at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by mortona42** [comment]
Ok, I forked your repo and tweaked the name to be commerce_usps/commerce_usps instead of drupal/usps: https://github.com/mortona42/commerce_usps/blob/master/composer.json

**Comment by mattwebdev** [comment]
made a pull request and pulled in your changes.
